project_id = "diolgjqstduyvilmrtng"

[functions.process-invoice]
verify_jwt = false

[functions.register-clock-entry]
verify_jwt = false

[functions.print-to-network]
verify_jwt = false

[functions.webapp-pedido-chat]
verify_jwt = false

[functions.link-guest-orders]
verify_jwt = false

[functions.send-order-push]
verify_jwt = false

[functions.calculate-delivery]
verify_jwt = false